all:
	cd palindrom && make all
	cd guess && make all

format-check:
	cd palindrom && make format-check
	cd guess && make format-check

format:
	cd palindrom && make format
	cd guess && make format

clean:
	cd palindrom && make clean
	cd guess && make clean